### ISSUE TITLE
Peer code review

### ISSUE THREAD

**Issue by maov19** [shubhambhoyar077/gdc_capstone#2]
Hi @shubhambhoyar077 !

Your page looks great! 🥇 
The only recomendation would be to add effects on the featured speakers site (optional)

**Comment by shafiuyushawu** [comment]
Hi @shubhambhoyar077 ,

Your webpage looks nice and responsive but I think there are a few optional changes to be made ♻️ 

Please I suggest you pin your hamburger to fixed position to avoid overflowing in different screen sizes

**Comment by shubhambhoyar077** [comment]
Fix overflow issue, hamburger and add effect on feature
